# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
numpy_array = np.zeros(10)
byte_size = numpy_array.nbytes
print(f'Memory Size of array: {byte_size} bytes')

Byte size of numpy array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# python -c 'import numpy as np; help(np.add)'

<ufunc 'add'>

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null_vector = np.zeros(10)
null_vector[4] = 1

null_vec = np.where(np.arange(10) == 4, 1,0)

print(null_vector)
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
vec = np.arange(1, 7)
reversed_vec = vec [:: -1]
print(reversed_vec)

[6 5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
# Create a 1D array with values 0-8
arr = np.arange(9)
# reshape into 3 by 3 matrix
matrix = arr.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]
print(indices)


[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [6]:
ran_arr = np.random.random((3, 3, 3))
print(ran_arr)

[[[3.07729882e-01 8.14959240e-02 1.00764138e-01]
  [3.17128212e-01 5.15588991e-01 8.11273632e-01]
  [9.11416657e-01 6.99107842e-01 6.97514952e-01]]

 [[2.68969151e-04 7.17864904e-01 1.35865369e-01]
  [7.29827389e-01 3.12308103e-01 2.60065855e-01]
  [3.39840246e-01 9.71716622e-01 1.37286623e-01]]

 [[6.60370025e-01 3.63173607e-01 1.66744837e-01]
  [7.40109508e-01 4.52270119e-01 6.89070853e-01]
  [6.11448722e-01 2.44998664e-01 2.46427330e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [7]:
ran_arr = np. random.random((10, 10))
print(ran_arr)

min_val, max_val = np.min(ran_arr), np.max(ran_arr)
print(f'Minimum Value: {min_val}, Maximum Value: {max_val}')

[[0.41364439 0.29613318 0.80123959 0.7470549  0.75559623 0.9523778
  0.04734954 0.6569316  0.93996036 0.8373375 ]
 [0.56351236 0.81271219 0.6607559  0.06954959 0.96381578 0.42464227
  0.71621654 0.6470467  0.40040499 0.15541198]
 [0.59235048 0.41373793 0.27644038 0.41643842 0.67918105 0.50264562
  0.69059868 0.99236546 0.08357064 0.45538239]
 [0.26831936 0.27889548 0.37015962 0.48626529 0.19364774 0.14295238
  0.97798441 0.81491137 0.7111464  0.50993655]
 [0.63456689 0.16655322 0.99173    0.87266811 0.25007995 0.6809152
  0.79007491 0.47577455 0.07512071 0.87392515]
 [0.68703184 0.78500112 0.38963808 0.19177971 0.35217043 0.78589666
  0.52291962 0.27271526 0.59709895 0.50883465]
 [0.76338806 0.61870764 0.01549293 0.77155349 0.44296888 0.20855208
  0.03247496 0.34469339 0.96302852 0.93255457]
 [0.74916096 0.01025118 0.6893237  0.51922973 0.26972347 0.88884221
  0.34487225 0.7234906  0.60959658 0.57029282]
 [0.64815602 0.459113   0.97903078 0.18871812 0.3383379  0.0506312
  0.87153595 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [8]:
ran_vec = np.random.random(30)
print(ran_vec)
mean_val = np.mean(ran_vec)
print(f'Mean Value: {mean_val}')

[0.81080875 0.26037474 0.58034222 0.26720306 0.76918071 0.81500289
 0.17667028 0.59588318 0.90970648 0.80051609 0.13874483 0.47212494
 0.89797963 0.64580573 0.53060242 0.19317213 0.54459351 0.09064039
 0.91211267 0.85245867 0.37201828 0.81962987 0.26862734 0.65627723
 0.50759107 0.54054266 0.88366503 0.30902538 0.19733051 0.39166824]
Mean Value: 0.5403432980395273


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [60]:

rows, cols = 2, 2

arr = np.zeros((rows, cols))
arr[0, :] = 0    
arr[1, :] = 1   
arr[:, 0] = 1 
arr[:, 1] = 0  

print(arr)

[[1. 0.]
 [1. 0.]]
