# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [24]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [20]:
A = np.ones(5)
B = np.ones(5)
np.add(A, B, out=B)  # B = A+B
np.divide(A, -2, out=A)  # A = -A/2
np.multiply(B, A, out=A)  # A = (A+B)*(-A/2)

print("A:", A)
print("B:", B)      
print("Result of A + B:", np.add(A, B))
print("Result of -A/2:", np.divide(A, -2))
print("Result of (A+B)*(-A/2):", np.multiply(B, A))


A: [-1. -1. -1. -1. -1.]
B: [2. 2. 2. 2. 2.]
Result of A + B: [1. 1. 1. 1. 1.]
Result of -A/2: [0.5 0.5 0.5 0.5 0.5]
Result of (A+B)*(-A/2): [-2. -2. -2. -2. -2.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0, 10, 10)

# Method 1: Truncation
int_part1 = np.trunc(Z)

# Method 2: Floor
int_part2 = np.floor(Z)

# Method 3: Cast to integer
int_part3 = Z.astype(int)

# Method 4: Ceiling adjusted for positive numbers
int_part4 = np.ceil(Z) - (Z % 1 != 0)
print("Original Array:", Z)
print("Truncated Integer Part:", int_part1)
print("Floored Integer Part:", int_part2)
print("Casted Integer Part:", int_part3)
print("Ceiling Adjusted Integer Part:", int_part4)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [17]:
matrix = np.tile(np.arange(5), (5, 1))
print("Tiled Matrix:\n", matrix)

Tiled Matrix:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [16]:
def generate_ints():
    for i in range(10):
        yield i

arr = np.fromiter(generate_ints(), dtype=int)
print("Array from generator:", arr)

Array from generator: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [14]:
vector = np.linspace(0, 1, 11, endpoint=False)[1:]
print("Vector:", vector)

Vector: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vec = np.random.rand(10)
vec.sort()
print("Sorted Vector:", vec)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
small_arr = np.array([1, 2, 3])
result = np.add.reduce(small_arr)
print("Result of np.add.reduce on small_arr:", result)

Result of np.add.reduce on small_arr: 6


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [10]:
A = np.random.rand(5)
B = np.random.rand(5)
equal = np.array_equal(A, B) 
close = np.allclose(A, B)  
print("A:", A)
print("B:", B)
print("Are A and B equal?", equal)
print("Are A and B close?", close)

A: [0.7840861  0.84531558 0.4808613  0.27334708 0.15125444]
B: [0.69081728 0.83496291 0.08212142 0.84866116 0.86710849]
Are A and B equal? False
Are A and B close? False


#### 43. Make an array immutable (read-only) (★★☆)

In [8]:
arr = np.zeros(5)
arr.flags.writeable = False
print(arr)
print("Is array writable?", arr.flags.writeable)

[0. 0. 0. 0. 0.]
Is array writable? False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
coords = np.random.rand(10, 2)
x, y = coords[:, 0], coords[:, 1]
r = np.sqrt(x**2 + y**2)      # Radius
theta = np.arctan2(y, x)      # Angle (radians)
polar = np.column_stack((r, theta))
print("Polar Coordinates:\n", polar)
print("Polar Coordinates (radians):\n", polar[:, 1])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np
vect = np.random.rand(10)
vect[vect.argmax()] = 0
print("Modified Vector:", vect)